### PR TITLE
Upgrade dependencies for PureScript 0.15.9

### PR DESCRIPTION
**Pull request by stephen-smith**
Passed all tests I could fine in the repo. ;)

### CODE REVIEW

**Comment by benjamin-hodgson** [comment]
Thank you very much! I'm merging this but I need to (re)learn how to publish Purescript packages. So might take a little while to get this up on the registry

**Comment by benjamin-hodgson** [comment]
Did this but looks like it hasn't been picked up yet, I'll check back tomorrow maybe https://github.com/purescript/registry/issues/302

**Comment by benjamin-hodgson** [comment]
I should also set up a CI workflow and some tests, probably

**Comment by stephen-smith** [comment]
> Did this but looks like it hasn't been picked up yet, I'll check back tomorrow maybe [purescript/registry#302](https://github.com/purescript/registry/issues/302)

I think SemVer requires a MAJOR version change (so, v1.0.0 instead of v0.6.0), since some of the type class instances were "removed": their requirements/context changed, so they might not be available at some types where they were previously available.  But, at this point, I don't see practical advantages to a version bump.

**Comment by benjamin-hodgson** [comment]
I guess that's true. Ah well. I think it's unlikely to matter, haha

**Pull request merged**
